### ISSUE TITLE
Action Bars not saving

### ISSUE THREAD

**Issue by Elitesparkle** [Lardeck/TalentLoadoutProfiles#1] opened 2023-02-19 10:10 UTC
When I switch Loadout, the icons on my Action Bars stay the same, even if clicked Save Action Bars.

**Comment by Lardeck** [comment] 2023-02-19 11:16
Do you use any AddOn like ElvUI to modify your Action Bars? And could you please send me your `ImprovedTalentLoadoutds.lua` file inside the `WTF\Account\YOURACCOUNTNAME\SavedVariables\` folder?

**Comment by Elitesparkle** [comment] 2023-02-19 11:23
No, I don't use any addon for Action Bars.

[ImprovedTalentLoadouts.zip](https://github.com/Lardeck/ImprovedTalentLoadouts/files/10776700/ImprovedTalentLoadouts.zip)

**Comment by Lardeck** [comment] 2023-02-19 12:59
I could only find one Loadout that has saved Action Bars: `Algeth'ar Academy` in the category `Season 1 (Fortify, No Explosive)` and i was able to load these Action Bars (besides the macros because obviously I don't have those). The only bug i could find is that I forgot to place mounts but that will be fixed with the next update. 

Do you use any Macro AddOn? Not sure how to assist further :(.

**Comment by Elitesparkle** [comment] 2023-02-19 17:35
Yes, I enabled it only for that Loadout for testing purposes.

No, I don't use any addon for macros.

I just found out that the bug only happens when "Automatically apply Loadout" is disabled!

**Comment by Lardeck** [comment] 2023-02-20 12:04
Oh ok that's is intended behaviour (at least for now). I could seperate the loadout and action bar options.

**Comment by Elitesparkle** [comment] 2023-02-20 13:02
I see. Thanks for the replies! Also, your addon is great.

**Comment by rency1012** [comment] 2023-11-22 14:24
Action bar switch not complete, just several marcos dont switch with loadouts after 10.2 
But loadouts created in 10.1 seems right. so what's wrong

**Comment by Lardeck** [comment] 2023-12-05 12:28
Should have been fixed in the latest update. It a Blizzard issue.

**Closed as completed by Lardeck** 2023-12-05 12:28 UTC
